# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: /#top
    weight: 10
  - name: Comment ça marche
    url: /#features
    weight: 20
  - name: À propos
    url: /#about
    weight: 30
  - name: Blog
    url: /blog/
    weight: 40
