# File: config/_default/menus.yaml
# Hopla - Navigation menus

# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Accueil
    url: /#top
    weight: 10
  
  - name: À propos
    url: /#about
    weight: 20
  
  - name: Blog
    url: /blog/
    weight: 30
  
  - name: Télécharger l'app
    url: '#download'
    weight: 40
