# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: custom

# SEO
marketing:
  seo:
    site_type: SoftwareApplication
    local_business_type: ''
    org_name: 'Hopla'
    description: 'La première app qui détecte les vols les moins chers depuis les aéroports locaux (Strasbourg, Bâle, Karlsruhe). Alerte prix gratuite et notifications en temps réel.'
    twitter: ''
  analytics:
    google_analytics: 'G-35WQ48G1L8'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    align: 'center'
    fixed_to_top: true
    logo:
      text: ''
      # Logo filename in `assets/media/` folder
      filename: 'logo.png'
    button:
      enable: true
      text: 'Télécharger Hopla'
      url: '#download'
    show_search: false
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: '© {year} Hopla. Pars d''ici, rêve plus loin. | bonjour@ho-pla.fr'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
